### ISSUE TITLE
Unified Linker

### ISSUE THREAD

**Issue by ingalls** [mapbox/pt2itp#520]
### Objective

We currently have 2 different versions of our linker code, one in rust used by `map`, and a more advanced token type supporting version in rust used by `conflate`. We should consolidate these two versions into a single codebase.As of now the rust version in default mode should be a drop in replacement for the js version.

- JS: https://github.com/mapbox/pt2itp/blob/master/lib/map/linker.js
- Rust: https://github.com/mapbox/pt2itp/blob/master/native/src/util/linker.rs

I anticipate this task will take 1 person at least 1 week between code, QA, and deploy.

### What is Linker?

The linker code is a module which accepts an text value and a list of potential text matches in geographic proximity to the text value. The code than uses the list to determine the best potential match out of the list.

### Tasks

- [ ] Rewrite match.js as a rust helper function (like `import_addr`, `import_nets`, etc) to wrap the rust linker and interact directly with the database, avoiding the need to make expensive calls between the rust/js code
- [ ] Ensure test parity between JS/Rust code, adding rust tests where possible
- [ ] Build and analyze full US build

### Risks

- Increased number of orphaned addresses due to poorer matching behavior.
  - I don't think this is likely and should be mitigated by test parity and comprehensive tests
  - We should scrutinize increases in orphaned addresses however to ensure they are not indicative of a problem
